# Dracut config for generating the sheng initramfs.

# Generic image, not tied to the build host hardware.
hostonly="no"
# Force adding the Qualcomm UFS drivers needed to boot from internal storage.
force_drivers+=" ufs_qcom ufshcd_pltfrm "
