# Ukify config for generating the sheng UKI.
[UKI]
Cmdline=console=tty0 root=PARTLABEL=linux rw rootwait quiet systemd.gpt_auto=no cryptomgr.notests systemd.show_status=auto loglevel=3
Stub=/usr/lib/systemd/boot/efi/linuxaa64.efi.stub
